# Site settings
title: code4me
description: 'coding challenges'
url: 'https://sreekanthkasani.github.io/code4me/'
baseurl: '/code4me/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'sreekanthkasani'
  email: sreekanthkasani22@gmail.com
  twitter_username: sreekanthkasani
  facebook_username: sreekanthkasani
  github_username:  sreekanthkasani
  linkedin_username:  sreekanthkasani

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
